source 'https://github.com/CocoaPods/Specs.git'
# was 9.0
platform :ios, '11.0'
use_frameworks!

target :'memedex' do
    # pod 'amplify-tools'
    pod 'Amplify'
    pod 'AWSPluginsCore'
    pod 'Amplify/Tools', '1.0.0'
    pod 'AmplifyPlugins/AWSPinpointAnalyticsPlugin'
    pod 'AmplifyPlugins/AWSCognitoAuthPlugin', '1.0.0'
    pod 'AWSCore'
    pod 'AWSAutoScaling'
    pod 'AWSCloudWatch'
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSDynamoDB'
    pod 'AWSEC2'
    pod 'AWSElasticLoadBalancing'
    pod 'AWSIoT'
    pod 'AWSKinesis'
    pod 'AWSLambda'
    pod 'AWSMachineLearning'
    pod 'AWSMobileAnalytics'
    pod 'AWSMobileClient', '2.13.4'
    pod 'AWSPinpoint'
    pod 'AWSS3'
    pod 'AWSSES'
    pod 'AWSSimpleDB'
    pod 'AWSSNS'
    pod 'AWSSQS'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKPlacesKit'
    pod 'AWSFacebookSignIn'
    pod 'AWSUserPoolsSignIn'
end
